src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
class Employee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank]
    private ?\DateTimeInterface $birth_date = null;

    #[ORM\Column(length: 255)]
    private ?string $picture_url = null;

    #[ORM\ManyToOne(inversedBy: 'employees')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Positions $position = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 18, scale: 2)]
    #[Assert\NotBlank(message: 'El salario es requerido')]
    #[Assert\Range(min: 3000, minMessage: 'El salario debe ser al menos de Q3,000.00')]
    private ?string $salary = null;

    #[ORM\ManyToOne(inversedBy: 'employees')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Store $store = null;

    #[ORM\Column(length: 255)]
    private ?string $public_image_id = null;

    /**
     * @var Collection<int, EmployeeAchievement>
     */
    #[ORM\OneToMany(targetEntity: EmployeeAchievement::class, mappedBy: 'employee')]
    private Collection $employeeAchievements;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El nombre es requerido')]
    #[Assert\Length(min: 1, max: 100, maxMessage: 'Máximo 100 cáracteres')]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    public function __construct()
    {
        $this->employeeAchievements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getPictureUrl(): ?string
    {
        return $this->picture_url;
    }

    public function setPictureUrl(string $picture_url): static
    {
        $this->picture_url = $picture_url;

        return $this;
    }

    public function getPosition(): ?Positions
    {
        return $this->position;
    }

    public function setPosition(?Positions $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(string $salary): static
    {
        $this->salary = $salary;

        return $this;
    }

    public function getStore(): ?Store
    {
        return $this->store;
    }

    public function setStore(?Store $store): static
    {
        $this->store = $store;

        return $this;
    }

    public function getPublicImageId(): ?string
    {
        return $this->public_image_id;
    }

    public function setPublicImageId(string $public_image_id): static
    {
        $this->public_image_id = $public_image_id;

        return $this;
    }

    /**
     * @return Collection<int, EmployeeAchievement>
     */
    public function getEmployeeAchievements(): Collection
    {
        return $this->employeeAchievements;
    }

    public function addEmployeeAchievement(EmployeeAchievement $employeeAchievement): static
    {
        if (!$this->employeeAchievements->contains($employeeAchievement)) {
            $this->employeeAchievements->add($employeeAchievement);
            $employeeAchievement->setEmployee($this);
        }

        return $this;
    }

    public function removeEmployeeAchievement(EmployeeAchievement $employeeAchievement): static
    {
        if ($this->employeeAchievements->removeElement($employeeAchievement)) {
            // set the owning side to null (unless already changed)
            if ($employeeAchievement->getEmployee() === $this) {
                $employeeAchievement->setEmployee(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }
}

src/Entity/EmployeeAchievement.php
<?php

namespace App\Entity;

use App\Repository\EmployeeAchievementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EmployeeAchievementRepository::class)]
class EmployeeAchievement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'La descripción es requerida')]
    #[Assert\Length(
        min: 10,
        max: 255,
        minMessage: 'La descripción necesita al menos 10 cáracteres',
        maxMessage: 'La descripción puede ser máximo de 255 cáracteres'
    )]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $achievement_type = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $achievement_date = null;

    #[ORM\ManyToOne(inversedBy: 'employeeAchievements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Employee $employee = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isAchievementType(): ?bool
    {
        return $this->achievement_type;
    }

    public function setAchievementType(bool $achievement_type): static
    {
        $this->achievement_type = $achievement_type;

        return $this;
    }

    public function getAchievementDate(): ?\DateTimeInterface
    {
        return $this->achievement_date;
    }

    public function setAchievementDate(\DateTimeInterface $achievement_date): static
    {
        $this->achievement_date = $achievement_date;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): static
    {
        $this->employee = $employee;

        return $this;
    }
}

src/Form/EmployeeType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use App\Entity\Positions;
use App\Entity\Store;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;

class EmployeeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $maxDate = (new \DateTime())->modify('-18 years');
        $builder
            ->add('birth_date', null, [
                'widget' => 'single_text',
                'label' => 'Fecha de nacimiento',
                'data' => $maxDate,
                'attr' => [
                    'class' => 'form-control',
                    'max' => $maxDate->format("Y-m-d")
                ]
            ])
            ->add('salary', null, [
                'attr' => [
                    'class' => 'form-control',
                ]
            ])
            ->add('name', null, [
                'attr' => [
                    'class' => 'form-control',
                ]
            ])
            ->add('lastname', null, [
                'attr' => [
                    'class' => 'form-control',
                ]
            ])
            ->add('position', EntityType::class, [
                'class' => Positions::class,
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'form-select',
                ]
            ])
            ->add('store', EntityType::class, [
                'class' => Store::class,
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'form-select',
                ]
            ])
            ->add('image', FileType::class, [
                'label' => 'Fotografía',
                'mapped' => false,
                'required' => $options['is_create'],
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Por favor, sube una imagen válida.',
                    ]),
                    new NotBlank([
                        'message' => 'Este campo es obligatorio.',
                        'groups' => $options['is_create'] ? ['Default'] : []
                    ])
                ],
                'attr' => [
                    'class' => 'form-control',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employee::class,
            'is_create' => false,
        ]);
    }
}

src/Controller/EmployeeController.php
<?php

namespace App\Controller;

use App\Entity\Employee;
use App\Form\EmployeeType;
use App\Repository\EmployeeAchievementRepository;
use App\Repository\EmployeeRepository;
use App\Service\CloudinaryService;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/employee')]
final class EmployeeController extends AbstractController
{

    #[Route(name: 'app_employee_index', methods: ['GET'])]
    public function index(EmployeeRepository $employeeRepository): Response
    {
        return $this->render('employee/index.html.twig', [
            'employees' => $employeeRepository->findAll(),
        ]);
    }

    #[Route('/pdf', name: 'app_employee_pdf_index', methods: ['GET'])]
    public function generatePdf(EmployeeRepository $employeeRepository): Response
    {
        $options = new Options();
        $options->set('defaultFont', 'Arial');
        $options->set('isRemoteEnabled', true);
        $dompdf = new Dompdf($options);


        $empleados = $employeeRepository->findAll();
        $total = $employeeRepository
            ->createQueryBuilder('e')
            ->select('sum(e.salary)');

        $html = $this->renderView('employee/empleados-pdf.html.twig', [
            'empleados' => $empleados,
            'total' => (float) $total->getQuery()->getSingleScalarResult(),
        ]);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        return new Response($dompdf->output(), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="empleados.pdf"',
        ]);
    }

    #[Route('/pdf-detail/{id}', name: 'app_employee_detail_pdf', methods: ['GET'])]
    public function generateDetailPdf(int $id, EmployeeRepository $employeeRepository): Response
    {
        $options = new Options();
        $options->set('defaultFont', 'Arial');
        $options->set('isRemoteEnabled', true);
        $dompdf = new Dompdf($options);

        $empleado = $employeeRepository->findOneBy(['id' => $id]);

        $html = $this->renderView('employee/empleados-detail-pdf.html.twig', [
            'empleado' => $empleado,
            'activities' => $empleado->getEmployeeAchievements(),
        ]);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        return new Response($dompdf->output(), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="empleado-detalle.pdf"',
        ]);
    }


    #[Route('/new', name: 'app_employee_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $employee = new Employee();
        $form = $this->createForm(EmployeeType::class, $employee, [
            'is_create' => true,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image')->getData();
            $cloudinaryService = new CloudinaryService();
            $uploadResult = $cloudinaryService->upload($imageFile);
            $employee->setPictureUrl($uploadResult['secure_url']);
            $employee->setPublicImageId($uploadResult['public_id']);
            $entityManager->persist($employee);
            $entityManager->flush();

            return $this->redirectToRoute('app_employee_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employee/new.html.twig', [
            'employee' => $employee,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employee_show', methods: ['GET'])]
    public function show(Employee $employee): Response
    {
        return $this->render('employee/show.html.twig', [
            'employee' => $employee,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_employee_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Employee $employee, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image')->getData();
            if ($imageFile) {
                $cloudinaryService = new CloudinaryService();
                $cloudinaryService->destroy($employee->getPublicImageId());
                $uploadResult = $cloudinaryService->upload($imageFile);
                $employee->setPictureUrl($uploadResult['secure_url']);
                $employee->setPublicImageId($uploadResult['public_id']);
            }
            $entityManager->flush();

            return $this->redirectToRoute('app_employee_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employee/edit.html.twig', [
            'employee' => $employee,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employee_delete', methods: ['POST'])]
    public function delete(Request $request, Employee $employee, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $employee->getId(), $request->getPayload()->getString('_token'))) {
            $cloudinaryService = new CloudinaryService();
            $cloudinaryService->destroy($employee->getPublicImageId());
            $entityManager->remove($employee);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_employee_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/employee/_delete_form.html.twig
<form method="post" action="{{ path('app_employee_delete', {'id': employee.id}) }}" onsubmit="return confirm('¿Estás seguro de eliminar el registro?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
    <button class="btn btn-danger delete-button" style="margin-top: 20px">Eliminar {{ ux_icon('ion:trash-outline') }} </button>
</form>

templates/employee/_form.html.twig
{{ form_start(form, { 'attr': {'novalidate': 'novalidate'} }) }}

    <div>
        {{ form_label(form.birth_date) }}
        {{ form_widget(form.birth_date) }}

        {% if form.birth_date.vars.errors|length > 0 %}
            <div class="alert alert-danger pb-0 mt-2">
                {{ form_errors(form.birth_date) }}
            </div>
        {% endif %}
    </div>


    <div class="mt-3">
        {{ "Salario" }}
        {{ form_widget(form.salary) }}

        {% if form.salary.vars.errors|length > 0 %}
            <div class="alert alert-danger pb-0 mt-2">
                {{ form_errors(form.salary) }}
            </div>
        {% endif %}
    </div>

    <div class="mt-3">
        {{ "Nombres" }}
        {{ form_widget(form.name) }}

        {% if form.name.vars.errors|length > 0 %}
            <div class="alert alert-danger pb-0 mt-2">
                {{ form_errors(form.name) }}
            </div>
        {% endif %}
    </div>

    <div class="mt-3">
        {{ "Apellidos" }}
        {{ form_widget(form.lastname) }}

        {% if form.name.vars.errors|length > 0 %}
            <div class="alert alert-danger pb-0 mt-2">
                {{ form_errors(form.lastname) }}
            </div>
        {% endif %}
    </div>

    <div class="mt-3">
        {{ "Puesto" }}
        {{ form_widget(form.position) }}

        {% if form.position.vars.errors|length > 0 %}
            <div class="alert alert-danger pb-0 mt-2">
                {{ form_errors(form.position) }}
            </div>
        {% endif %}
    </div>

    <div class="mt-3">
        {{ "Tienda" }}
        {{ form_widget(form.store) }}

        {% if form.store.vars.errors|length > 0 %}
            <div class="alert alert-danger pb-0 mt-2">
                {{ form_errors(form.store) }}
            </div>
        {% endif %}
    </div>

    <div class="mt-3">
        {{ form_label(form.image) }}
        {{ form_widget(form.image) }}

        {% if form.image.vars.errors|length > 0 %}
            <div class="alert alert-danger pb-0 mt-2">
                {{ form_errors(form.image) }}
            </div>
        {% endif %}
    </div>

    <div class="save-button">
        <button class="btn btn-dark">{{ button_label|default('Guardar') }}</button>
    </div>
    
{{ form_end(form) }}

templates/employee/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar empleado{% endblock %}

{% block body %}
    <h1>Editar empleado</h1>

    <div>
        <img class="employee-image" src="{{ employee.pictureUrl }}" alt="" />
    </div>

    {{ include('employee/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <div class="button-container">
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_index') }}"> Regresar a la lista </a>
        </button>
    </div>

    {{ include('employee/_delete_form.html.twig') }}
{% endblock %}

templates/employee/empleados-detail-pdf.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee index{% endblock %}
{% block body %}

    <head>
        <meta charset="utf-8">
        <title>Detalle empleado</title>
        <style>
            body {
                font-family: sans-serif;
            }
            table {
                width: 100%;
                border-collapse: collapse;
            }
            table, th, td {
                border: 1px solid black;
            }
            th, td {
                padding: 8px;
                text-align: left;
                max-width: 300px;
                white-space: normal;
                word-wrap: break-word;
            }
            img {
                max-width: 300px;
                height: auto;
            }
        </style>
    </head>
    <body>
    <h1>Empleado: {{ empleado.name }} {{ empleado.lastname }}</h1>
    <div>
        <img src="{{ empleado.pictureUrl }}" alt=""  style="width: 200px; height: auto;"/>
    </div>
    <ul>
        <li>Salario: <b>{{ empleado.salary | format_currency('GTQ') }}</b></li>
        <li>Puesto: <b>{{ empleado.position.name }}</b></li>
        <li>Tienda: <b>{{ empleado.store.name }}</b></li>
        <li>Fecha de nacimiento: <b>{{ empleado.birthDate | date('d/m/Y') }}</b></li>
    </ul>
    <table>
        <thead>
        <tr>
            <th>Tipo de observación</th>
            <th>Descripción</th>
            <th>Hora y Fecha</th>
        </tr>
        </thead>
        <tbody>
        {% for actividad in activities %}
            <tr>
                <td>{{ actividad.achievementType ? 'Logro' : 'Llamada de atención' }}</td>
                <td>{{ actividad.description }}</td>
                <td>{{ actividad.achievementDate | date('H:m:s d/m/Y') }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </body>
{% endblock %}

templates/employee/empleados-pdf.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee index{% endblock %}
{% block body %}

<head>
    <meta charset="utf-8">
    <title>Lista de Empleados</title>
    <style>
        h1 {
             font-family: sans-serif;
        }
        body {
            font-family: sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
    </style>
</head>
<body>
<h1>Lista de Empleados</h1>
<table>
    <thead>
    <tr>
        <th>Fotografía</th>
        <th>Nombre Completo</th>
        <th>Salario</th>
        <th>Puesto</th>
        <th>Tienda</th>
        <th>Fecha de nacimiento</th>
    </tr>
    </thead>
    <tbody>
    {% for empleado in empleados %}
        <tr>
            <td><img src="{{ empleado.pictureUrl }}" alt="Foto" style="width: 50px; height: auto;"></td>
            <td>{{ empleado.name }} {{ empleado.lastname }}</td>
            <td>{{ empleado.salary | format_currency('GTQ') }}</td>
            <td>{{ empleado.position.name }}</td>
            <td>{{ empleado.store.name }}</td>
            <td>{{ empleado.birthDate ? empleado.birthDate|date('d/m/Y') : '' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<h4 class="mt-5">Total salarios <span class="badge bg-secondary"> {{ total | format_currency('GTQ') }} </span></h4>
</body>
{% endblock %}

templates/employee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Empleados{% endblock %}

{% block body %}
    <h1>Empleados</h1>

    {% if employees|length > 0 %}
        <table class="table">
            <thead>
                <tr>
                    <th>Imagen</th>
                    <th>Id</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Fecha de nacimiento</th>
                    <th>Salario</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
            {% for employee in employees %}
                <tr>
                    <td> <img class="employee-image" src="{{ employee.pictureUrl }}" alt="" /> </td>
                    <td>{{ employee.id }}</td>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.lastname }}</td>
                    <td>{{ employee.birthDate ? employee.birthDate|date('d/m/Y') : '' }}</td>
                    <td>{{ employee.salary | format_currency('GTQ') }}</td>
                    <td>
                        <a class="eye" href="{{ path('app_employee_show', {'id': employee.id}) }}">{{ ux_icon('ion:eye-outline') }}</a>
                        <a href="{{ path('app_employee_edit', {'id': employee.id}) }}">{{ ux_icon('ion:create-outline') }}</a>
                        <div>
                            <a href="{{ path('app_employee_achievement_index', { 'employeeId': employee.id }) }}"> Observaciones {{ ux_icon('ion:reader-outline') }} </a>
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">"No se encontraron registros</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="not-found-data">
            <img src="{{ asset('images/employee.png') }}" alt="No se encontraron registros">
            <p>No hay empleados ingresados.</p>
        </div>
    {% endif %}

    <div class="button-container">
        <button type="button" class="btn btn-dark">
          <a href="{{ path('app_employee_new') }}">Ingresar empleado</a>
        </button>
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_pdf_index') }}">Reporte general</a>
        </button>
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_achievement_all_pdf') }}">Reporte observaciones</a>
        </button>
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_achievements_pdf') }}">Reporte logros</a>
        </button>
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_warnings_pdf') }}">Reporte llamadas de atención</a>
        </button>
    </div>
    <div class="button-container" style="margin-top: 20px">
        <button type="button" class="btn btn-dark">
          <a href="{{ path('app_index') }}"> Regresar </a>
        </button>
    </div>
{% endblock %}

templates/employee/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo empleado{% endblock %}

{% block body %}
    <h1>Ingresar Empleado</h1>

    {{ include('employee/_form.html.twig') }}

    <div class="button-container">
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_index') }}"> Regresar a la lista </a>
        </button>
    </div>
 
{% endblock %}

templates/employee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Empleado{% endblock %}

{% block body %}
    <h1>Empleado</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Imagen</th>
            <td><img class="employee-image" src="{{ employee.pictureUrl }}" class="img-fluid" alt="" /></td>
        </tr>
            <tr>
                <th>Id</th>
                <td>{{ employee.id }}</td>
            </tr>
           <tr>
               <th>Nombres</th>
               <td>{{ employee.name }}</td>
           </tr>
            <tr>
                <th>Apellidos</th>
                <td>{{ employee.lastname }}</td>
            </tr>
            <tr>
                <th>Fecha de nacimiento</th>
                <td>{{ employee.birthDate ? employee.birthDate|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Salario</th>
                <td>{{ employee.salary | format_currency('GTQ') }}</td>
            </tr>
            <tr>
                <th>Tienda</th>
                <td>{{ employee.store.name }}</td>
            </tr>
            <tr>
                <th>Puesto</th>
                <td>{{ employee.position.name }}</td>
            </tr>
        </tbody>
    </table>

    <div class="button-container">
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_index') }}"> Regresar a la lista </a>
        </button>
        <button type="button" class="btn btn-dark">
           <a href="{{ path('app_employee_edit', {'id': employee.id}) }}">Editar</a>
        </button>
        <button type="button" class="btn btn-dark">
            <a href="{{ path('app_employee_detail_pdf', {'id': employee.id}) }}">Reporte detalle empleado</a>
        </button>
    </div>
    {{ include('employee/_delete_form.html.twig') }}
{% endblock %}